Repository umr-lops/cdsodatacli, pull requests merged in 2023-11, with the labels that each got.

#28 Draft Pypi automated release
  .github/workflows/build.yml
  .github/workflows/greetings.yml
  .github/workflows/publish.yml
  .github/workflows/release-drafter.yml
  cdsodatacli/__init__.py
  cdsodatacli/__main__.py
  cdsodatacli/clone.py
  cdsodatacli/query.py
  docs/Makefile
  docs/_static/css/cdsodatacli.css
  docs/basic_api.rst
  docs/conf.py
  docs/examples/basic_usage.ipynb
  docs/index.rst
  docs/installing.rst
  pyproject.toml
Labels: enhancement

#35 many bugfix before `cache` pull request merging
  cdsodatacli/query.py
Labels: bug, enhancement

#33 Add cache
  .gitignore
  cdsodatacli/query.py
  tests/query_test.py
Labels: enhancement

#39 Download feature
  cdsodatacli/config.yml
  cdsodatacli/download.py
  cdsodatacli/fetch_access_token.py
  cdsodatacli/query.py
  cdsodatacli/utils.py
  docs/index.rst
  pyproject.toml
  tests_metiers/test_download_WV.py
Labels: enhancement

#44 add pyyaml
  pyproject.toml
Labels: bug
